spring:
  application:
    name: juha-backend
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/juha_car?verifyServerCertificate=false&useSSL=true
    username: dev
    password: 
  data:
    rest:
      base-path: /api  
    
server:
  port: 8082
  tomcat:
    max-threads: 100